# Generated by Django 3.0.3 on 2020-03-22 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air', models.ForeignKey(db_column='shipping_air', on_delete=django.db.models.deletion.CASCADE, to='shipping.Air')),
                ('book', models.ForeignKey(db_column='product_book', on_delete=django.db.models.deletion.CASCADE, to='product.Book')),
                ('e_book', models.ForeignKey(db_column='product_e_book', on_delete=django.db.models.deletion.CASCADE, to='product.EBook')),
                ('ground', models.ForeignKey(db_column='shipping_ground', on_delete=django.db.models.deletion.CASCADE, to='shipping.Ground')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('sea', models.ForeignKey(db_column='shipping_sea', on_delete=django.db.models.deletion.CASCADE, to='shipping.Sea')),
            ],
        ),
    ]
