# Generated by Django 3.0.3 on 2020-03-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200322_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='e_book',
        ),
    ]
