# Generated by Django 3.0.3 on 2020-07-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_delete_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='product',
        ),
    ]
