# Generated by Django 3.0.3 on 2020-07-04 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200704_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='user',
        ),
    ]
