# Generated by Django 3.0.3 on 2020-03-22 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0004_remove_orderdetail_e_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='e_book',
            field=models.ForeignKey(db_column='product_e_book', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.EBook'),
        ),
    ]
