# Generated by Django 3.0.3 on 2020-03-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='in cents', null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='in cents', null=True),
        ),
    ]
