# Generated by Django 3.0.3 on 2020-07-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200705_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default',
        ),
    ]
