# Generated by Django 3.0.3 on 2020-08-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_set', to='product.Product'),
        ),
    ]
