# Generated by Django 3.0.3 on 2020-04-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_delete_orderdetail'),
        ('shipping', '0002_auto_20200322_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='air', to='order.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ground',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ground', to='order.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sea',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sea', to='order.Order'),
            preserve_default=False,
        ),
    ]
